# Uncomment the next line to define a global platform for your project
#platform :ios, '12.0'

target 'MMRDA' do
# Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!

  # Pods for MMRDA
         pod 'IQKeyboardManagerSwift'
         pod 'Firebase/Messaging'
         #pod 'ReachabilitySwift' # Reachability Swift (Internet Connection Check)
         pod 'Localize-Swift' # For Localization String
         pod 'Alamofire'
         pod 'FAPanels' # For SideMenu
         pod 'SVProgressHUD'
         pod 'DropDown'
         pod 'GooglePlaces'
         pod 'GooglePlacePicker'
         pod 'ACFloatingTextfield-Swift'
         pod 'SDWebImage'
#         , '~> 5.0'
         pod 'CountryPickerView'
         pod "ImageSlideshow/SDWebImage"
         #pod 'EFQRCode', '~> 6.2.1'
          pod 'QRCode'
          pod 'Toast'
          
         #pod 'Toast-Swift', '~> 5.0.1'
         post_install do |installer|
           installer.pods_project.targets.each do |target|
             target.build_configurations.each do |config|
               config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
             end
           end
         end


       target 'MMRDATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MMRDAUITests' do
    # Pods for testing
  end

end
